### ISSUE TITLE
Can a trained model be provided?

### ISSUE THREAD

**Issue by OroelNaitec** [sahilkhose/FloodNet#2]
Hi,

Can you provide the trained model to make new predictions?

I am trying to use the DeepLabv3+ model with some areal images I took but training the model is getting hard:

The pretrained model (MyDrive/models/abhi_sudo_full_2-pretrained_preproc_1-deeplabv3+-ep_5-0.001-8.p) is not provided and trainng from zero doesn't seem to be an option

**Comment by sahilkhose** [comment]
Hi,
Even if we provide the models, you will have to train the model on your desired dataset (if it is not FloodNet).
What do you mean training from zero doesn't seem to be an option? 
All our training was done on Google Colab. You mentioned it runs out of RAM when you try to train it. 
1. You should not be running out of RAM because of the model, check if it is loaded on GPU
2. To reduce the RAM consumed, try reducing the input dimensions of the image
3. To avoid any other memory issues on GPU, try reducing the batch size or hidden dimensions of the segmentation model. You can change the backbone of the segmentation model to reduce the number of parameters
